/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-06-17 23:50:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import user.UserDAO;
import user.User;
import post.PostDAO;
import post.Post;
import review.Review;
import review.ReviewDAO;
import java.util.ArrayList;

public final class postDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("user.User");
    _jspx_imports_classes.add("review.Review");
    _jspx_imports_classes.add("post.PostDAO");
    _jspx_imports_classes.add("user.UserDAO");
    _jspx_imports_classes.add("post.Post");
    _jspx_imports_classes.add("review.ReviewDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/promotion.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/article.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/room-info.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/floating.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/swiper-bundle.min.css\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/favicon.png\"  type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css\">\r\n");
      out.write("    <script type=\"module\" src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js\"></script>\r\n");
      out.write("    <script nomodule src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js\"></script>\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	String ID = null;
		if(session.getAttribute("ID") != null){
			ID = (String) session.getAttribute("ID");
		}
		int postID = 0;
		if (request.getParameter("postID") != null){
			postID = Integer.parseInt(request.getParameter("postID"));
		}
		if (postID == 0) {
			PrintWriter script = response.getWriter();
			script.println("<script>");
			script.println("alert('존재하지 않는 게시글 입니다.')");
			script.println("history.back()");
			script.println("</script>");
		}
		PostDAO postDAO = new PostDAO();
		postDAO.viewCountUp(postID);
		Post post = postDAO.getPostDetail(postID);
		String postReserve = "reserve.jsp?postID=" + post.getPOST_NUM();
		String titleMain = "images/mainImage/" + post.getPHOTO();
		String score = Double.toString(Math.round(post.getSCORE() * 10) / 10.0);
		String postContents = post.getPOST_CONTENTS().replace("\r\n", "<br>");
		String postDate = post.getPOST_DATE().substring(0, 10);
		
		UserDAO userDAO = new UserDAO();
		User user = userDAO.getUserInfo(ID);
	
      out.write("\r\n");
      out.write("	location.reload()\r\n");
      out.write("    <div class=\"floating\">\r\n");
      out.write("        <a href=\"/\"><div class=\"topBtn\">\r\n");
      out.write("            <i class=\"ri-arrow-up-s-line\"></i>\r\n");
      out.write("        </div></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <a href=\"searchmain.jsp\" class=\"logo\"><img src=\"images/logo.png\"></a>\r\n");
      out.write("            <form action=\"\" class=\"search-wrapper\">\r\n");
      out.write("                <input type=\"text\" name=\"\" placeholder=\"공간을 검색해보세요\" class=\"searchBar\">\r\n");
      out.write("                <button type=\"submit\" class=\"searchBtn\">\r\n");
      out.write("                    <ion-icon name=\"search-sharp\"></ion-icon>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            ");

    			if(ID == null){
   			
      out.write("\r\n");
      out.write("    			<a href=\"login.html\"><div class=\"loginBtn\"><p>로그인</p></div></a>\r\n");
      out.write("    		");

    			} else {
   			
      out.write("\r\n");
      out.write("    			<div class=\"myIcons\">\r\n");
      out.write("                <a href=\"myPostView.jsp\"><div class=\"myIcon\">\r\n");
      out.write("                    <i class=\"ri-file-list-line\"></i>\r\n");
      out.write("                </div></a>\r\n");
      out.write("                <a href=\"rentView.jsp\"><div class=\"myIcon\">\r\n");
      out.write("                    <i class=\"ri-task-line\"></i>\r\n");
      out.write("                </div></a>\r\n");
      out.write("                <a href=\"reserveView.jsp\"><div class=\"myIcon\">\r\n");
      out.write("                    <i class=\"ri-draft-line\"></i>\r\n");
      out.write("                </div></a>\r\n");
      out.write("                <a href=\"myInfo.jsp\"><div class=\"myIcon\">\r\n");
      out.write("                    <i class=\"ri-emotion-happy-line\"></i>\r\n");
      out.write("                </div></a>\r\n");
      out.write("            </div>\r\n");
      out.write("    		");

    			}	
    		
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <main>\r\n");
      out.write("        <section class=\"article\">\r\n");
      out.write("            <div class=\"article-wrapper\">\r\n");
      out.write("                <div class=\"r-i-wrapper\">\r\n");
      out.write("                    <div class=\"r-i-header\">\r\n");
      out.write("                        <div class=\"r-i-slider\">\r\n");
      out.write("                            <div class=\"swiper mySwiper\">\r\n");
      out.write("                                <div class=\"swiper-wrapper\">\r\n");
      out.write("                                    <div class=\"swiper-slide\">\r\n");
      out.write("                                        <img src=");
      out.print( titleMain );
      out.write(">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"swiper-pagination\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"r-i-text\">\r\n");
      out.write("                            <div class=\"a-box-title\">\r\n");
      out.write("                                <h1 class=\"product\">");
      out.print( post.getTITLE() );
      out.write("</h1>\r\n");
      out.write("                                <h5 class=\"address\">");
      out.print( post.getADDRESS() );
      out.write("</h5>\r\n");
      out.write("                                <p class=\"spaceInfo\">\r\n");
      out.write("                                    ");
      out.print( post.getINFO() );
      out.write("\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <h2 class=\"price\">₩");
      out.print( post.getPRICE() );
      out.write(" <span class=\"time\">/ ");
      out.print( post.getRENTAL_TIME() );
      out.write("</span></h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"a-box-under\">\r\n");
      out.write("                                <div class=\"a-box-text\">\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <span class=\"date\"><ion-icon name=\"cloud-upload-sharp\"></ion-icon>");
      out.print(postDate );
      out.write("</span>\r\n");
      out.write("                                        <span class=\"view\"><ion-icon name=\"eye-sharp\"></ion-icon>");
      out.print(post.getVIEW_COUNT() );
      out.write("</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"star\">\r\n");
      out.write("                                        <h4>\r\n");
      out.write("                                            ★");
      out.print(score );
      out.write("점\r\n");
      out.write("                                        </h4>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");

    								if(ID != null){
   								
      out.write("\r\n");
      out.write("    								<a href=");
      out.print(postReserve);
      out.write(">\r\n");
      out.write("                                    <button class=\"moreBtn\"><p>예약하기</p></button>\r\n");
      out.write("                                </a>\r\n");
      out.write("    							");

    								} else {
    								}
   								
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"r-i-main\">\r\n");
      out.write("                        <div class=\"r-i-main-text\">\r\n");
      out.write("                            <h1>공간소개</h1>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                ");
      out.print( postContents );
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

    					if(ID == null){
    					} else {
   					
      out.write("\r\n");
      out.write("                    <div class=\"r-i-main\">\r\n");
      out.write("                        <div class=\"r-i-main-text\">\r\n");
      out.write("                            <div class=\"write-form\">\r\n");
      out.write("                            <form action=\"reviewWirteAction.jsp\">\r\n");
      out.write("                                <div class=\"star-rating\">\r\n");
      out.write("                                    <div class=\"ratingControl\">\r\n");
      out.write("                                        <input id=\"score100\" class=\"ratingControl__radio\" type=\"radio\" name=\"SCORE\" value=\"5.0\" />\r\n");
      out.write("                                        <label for=\"score100\" class=\"ratingControl__star\" title=\"Five Stars\"></label>\r\n");
      out.write("                                        <input id=\"score90\" class=\"ratingControl__radio\" type=\"radio\" name=\"SCORE\" value=\"4.5\" />\r\n");
      out.write("                                        <label for=\"score90\" class=\"ratingControl__star\" title=\"Four & Half Stars\"></label>\r\n");
      out.write("                                        <input id=\"score80\" class=\"ratingControl__radio\" type=\"radio\" name=\"SCORE\" value=\"4.0\" />\r\n");
      out.write("                                        <label for=\"score80\" class=\"ratingControl__star\" title=\"Four Stars\"></label>\r\n");
      out.write("                                        <input id=\"score70\" class=\"ratingControl__radio\" type=\"radio\" name=\"SCORE\" value=\"3.5\" />\r\n");
      out.write("                                        <label for=\"score70\" class=\"ratingControl__star\" title=\"Three & Half Stars\"></label>\r\n");
      out.write("                                        <input id=\"score60\" class=\"ratingControl__radio\" type=\"radio\" name=\"SCORE\" value=\"3.0\" />\r\n");
      out.write("                                        <label for=\"score60\" class=\"ratingControl__star\" title=\"Three Stars\"></label>\r\n");
      out.write("                                        <input id=\"score50\" class=\"ratingControl__radio\" type=\"radio\" name=\"SCORE\" value=\"2.5\" />\r\n");
      out.write("                                        <label for=\"score50\" class=\"ratingControl__star\" title=\"Two & Half Stars\"></label>\r\n");
      out.write("                                        <input id=\"score40\" class=\"ratingControl__radio\" type=\"radio\" name=\"SCORE\" value=\"2.0\" />\r\n");
      out.write("                                        <label for=\"score40\" class=\"ratingControl__star\" title=\"Two Stars\"></label>\r\n");
      out.write("                                        <input id=\"score30\" class=\"ratingControl__radio\" type=\"radio\" name=\"SCORE\" value=\"1.5\" />\r\n");
      out.write("                                        <label for=\"score30\" class=\"ratingControl__star\" title=\"One & Half Star\"></label>\r\n");
      out.write("                                        <input id=\"score20\" class=\"ratingControl__radio\" type=\"radio\" name=\"SCORE\" value=\"1.0\" />\r\n");
      out.write("                                        <label for=\"score20\" class=\"ratingControl__star\" title=\"One Star\"></label>\r\n");
      out.write("                                        <input id=\"score10\" class=\"ratingControl__radio\" type=\"radio\" name=\"SCORE\" value=\"0.5\" />\r\n");
      out.write("                                        <label for=\"score10\" class=\"ratingControl__star\" title=\"Half Star\"></label>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                	<input type=\"hidden\" id=\"POST_NUM\" name=\"POST_NUM\" value=\"");
      out.print(postID);
      out.write("\">\r\n");
      out.write("                                	<input type=\"hidden\" id=\"NICKNAME\" name=\"NICKNAME\" value=\"");
      out.print(user.getNICKNAME());
      out.write("\">\r\n");
      out.write("                                	<input type=\"hidden\" id=\"EMAIL\" name=\"EMAIL\" value=\"");
      out.print(user.getEMAIL());
      out.write("\">\r\n");
      out.write("                                    <textarea name=\"REVIEW_CONTENTS\" class=\"write-input\" placeholder=\"리뷰내용을 입력하세요\"></textarea>\r\n");
      out.write("                                    <button type=\"submit\" class=\"writesubmitBtn\"><p>작성하기</p></button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

    					}
                    
      out.write("\r\n");
      out.write("                    <div class=\"r-i-review\">\r\n");
      out.write("                        <div class=\"review-wrapper\">\r\n");
      out.write("                        ");

                			ReviewDAO reviewDAO = new ReviewDAO();
                        	ArrayList<Review> list = reviewDAO.getReview(postID);
                			for(int i = 0; i < list.size(); i++){
                				String userProfile = "images/userProfile/" + list.get(i).getEMAIL() + ".jpg";
                				String SCORE = list.get(i).getSCORE();
                				if(list.get(i).getSCORE().equals(".5")){
                					SCORE = "0.5";
                				}
                		
      out.write("\r\n");
      out.write("                            <div class=\"review-box\">\r\n");
      out.write("                                <div class=\"r-b-top\">\r\n");
      out.write("                                    <div class=\"r-profile\">\r\n");
      out.write("                                        <img src= ");
      out.print( userProfile);
      out.write(" >\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"r-title\">\r\n");
      out.write("                                        <h1>\r\n");
      out.write("                                            ");
      out.print( list.get(i).getNICKNAME());
      out.write("\r\n");
      out.write("                                        <div class=\"star\">\r\n");
      out.write("                                            <h4>\r\n");
      out.write("                                                ★");
      out.print( SCORE);
      out.write("점\r\n");
      out.write("                                            </h4>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"r-b-text\">\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        ");
      out.print( list.get(i).getREVIEW_CONTENTS());
      out.write("\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                         ");

                			}
                         
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-wrapper\">\r\n");
      out.write("            <p>\r\n");
      out.write("                Copyright (C) 2022 All Rights Reserved.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    var swiper = new Swiper(\".mySwiper\", {\r\n");
      out.write("        slidesPerView: 1,\r\n");
      out.write("        spaceBetween: 30,\r\n");
      out.write("        loop: true,\r\n");
      out.write("        pagination: {\r\n");
      out.write("            el: \".swiper-pagination\",\r\n");
      out.write("            clickable: true,\r\n");
      out.write("        },\r\n");
      out.write("        autoplay: {\r\n");
      out.write("            delay: 2500,\r\n");
      out.write("            disableOnInteraction: false,\r\n");
      out.write("        },\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write(" \r\n");
      out.write("        $(\".floating\").hide();\r\n");
      out.write("        $(function() {\r\n");
      out.write(" \r\n");
      out.write("            $(window).scroll(function() {\r\n");
      out.write("                if ($(this).scrollTop() > 200) {\r\n");
      out.write("                    $('.floating').fadeIn();\r\n");
      out.write("                } else {\r\n");
      out.write("                    $('.floating').fadeOut();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write(" \r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    $(function () {\r\n");
      out.write("        $('.floating a').click(function (e) {\r\n");
      out.write("            $.scrollTo(this.hash || 0, 500); /* 속도 절, 숫자가 작을수록 빠름 */\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    if (window.navigator.userAgent.match(/MSIE|Internet Explorer|Trident/i)) {\r\n");
      out.write("        // IE!!\r\n");
      out.write("        window.location = 'https://support.microsoft.com/ko-kr/office/%ec%97%b0%ea%b2%b0%ed%95%98%eb%a0%a4%eb%8a%94-%ec%9b%b9-%ec%82%ac%ec%9d%b4%ed%8a%b8%ea%b0%80-internet-explorer%ec%97%90%ec%84%9c-%ec%9e%91%eb%8f%99%ed%95%98%ec%a7%80-%ec%95%8a%ec%8a%b5%eb%8b%88%eb%8b%a4-8f5fc675-cd47-414c-9535-12821ddfc554?ui=ko-kr&rs=ko-kr&ad=kr';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
