/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-06-17 23:56:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import reserve.Reserve;
import reserve.ReserveDAO;
import java.util.ArrayList;

public final class rentView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("reserve.Reserve");
    _jspx_imports_classes.add("reserve.ReserveDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"키워드\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"키워드\">\r\n");
      out.write("    <meta property=\"og:url\" content=\"도메인\">\r\n");
      out.write("    <meta property=\"og:title\" content=\"키워드\">\r\n");
      out.write("    <meta property=\"og:description\" content=\"사이트설명\">\r\n");
      out.write("    <meta property=\"og:image\" content=\"대표이미지\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/promotion.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/article.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/floating.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/aos@next/dist/aos.css\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/favicon.png\"  type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css\">\r\n");
      out.write("    <script type=\"module\" src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js\"></script>\r\n");
      out.write("    <script nomodule src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js\"></script>\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		String ID = null;
		if(session.getAttribute("ID") != null){
			ID = (String) session.getAttribute("ID");
		}
	
      out.write("\r\n");
      out.write("    <div class=\"floating\">\r\n");
      out.write("        <a href=\"/\"><img src=\"images/top.png\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <a href=\"searchmain.jsp\" class=\"logo\"><img src=\"images/logo.png\"></a>\r\n");
      out.write("            <form action=\"\" class=\"search-wrapper\">\r\n");
      out.write("                <input type=\"text\" name=\"searchText\" placeholder=\"공간을 검색해보세요\" class=\"searchBar\">\r\n");
      out.write("                <button type=\"submit\" class=\"searchBtn\">\r\n");
      out.write("                    <ion-icon name=\"search-sharp\"></ion-icon>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            ");

    			if(ID == null){
   			
      out.write("\r\n");
      out.write("    			<a href=\"login.html\"><div class=\"loginBtn\"><p>로그인</p></div></a>\r\n");
      out.write("    		");

    			} else {
   			
      out.write("\r\n");
      out.write("    			<div class=\"myIcons\">\r\n");
      out.write("                <a href=\"myPostView.jsp\"><div class=\"myIcon\">\r\n");
      out.write("                    <i class=\"ri-file-list-line\"></i>\r\n");
      out.write("                </div></a>\r\n");
      out.write("                <a href=\"rentView.jsp\"><div class=\"myIcon\">\r\n");
      out.write("                    <i class=\"ri-task-line\"></i>\r\n");
      out.write("                </div></a>\r\n");
      out.write("                <a href=\"reserveView.jsp\"><div class=\"myIcon\">\r\n");
      out.write("                    <i class=\"ri-draft-line\"></i>\r\n");
      out.write("                </div></a>\r\n");
      out.write("                <a href=\"myInfo.jsp\"><div class=\"myIcon\">\r\n");
      out.write("                    <i class=\"ri-emotion-happy-line\"></i>\r\n");
      out.write("                </div></a>\r\n");
      out.write("            </div>\r\n");
      out.write("    		");

    			}	
    		
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <main>\r\n");
      out.write("        <section class=\"article\">\r\n");
      out.write("            <div class=\"article-wrapper\">\r\n");
      out.write("                <div class=\"article-title\">\r\n");
      out.write("                    <h1>\r\n");
      out.write("                        <span class=\"city\">대여 내역</span>\r\n");
      out.write("                    </h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"article-box-wrapper\">\r\n");
      out.write("                	");

                		ReserveDAO reserveDAO = new ReserveDAO();
                		ArrayList<Reserve> list = reserveDAO.getSearch(ID,"RENT_USEREMAIL");
                		for(int i = 0; i < list.size(); i++){
                			String titleMain = "images/mainImage/" + reserveDAO.reservePhoto(list.get(i).getPOST_NUM());
                			String postDetail = "postDetail.jsp?postID=" + list.get(i).getPOST_NUM();
                			String reserveNumber = list.get(i).getRESERVE_NUM();
                			String postDate = list.get(i).getRESERVE_DATE().substring(0, 10);
                	
      out.write("\r\n");
      out.write("                    <div class=\"article-box\">\r\n");
      out.write("                        <img src=");
      out.print(titleMain);
      out.write(" class=\"a-box-image\">\r\n");
      out.write("                        <div class=\"a-box-info\">\r\n");
      out.write("                            <div class=\"a-box-title\">\r\n");
      out.write("                                <h1 class=\"product\">");
      out.print(list.get(i).getPOST_TITLE());
      out.write("</h1>\r\n");
      out.write("                                <h5 class=\"address\">예약자 : ");
      out.print(list.get(i).getEMAIL());
      out.write("</h5>\r\n");
      out.write("                                <h5 class=\"address\">대여자 : ");
      out.print(list.get(i).getRENT_USEREMAIL());
      out.write("</h5>\r\n");
      out.write("                                <h5 class=\"address\">예약 번호 : ");
      out.print(list.get(i).getRESERVE_NUM());
      out.write("</h5>\r\n");
      out.write("                                <h2 class=\"price\">₩");
      out.print(list.get(i).getPRICE());
      out.write(" <span class=\"time\">/ ");
      out.print(postDate);
      out.write("</span></h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"a-box-under\">\r\n");
      out.write("                                <a href= ");
      out.print( postDetail);
      out.write(" >\r\n");
      out.write("                                    <button class=\"moreBtn\" ><p>게시글보기</p></button>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                    <a href= \"rentDeleteAction.jsp?reserveID=");
      out.print(list.get(i).getRESERVE_NUM());
      out.write("\" >\r\n");
      out.write("                                   		<button onclick=\"return confirm('정말로 취소하시겠습니까?')\" class=\"moreBtn\" style=\"background-color:red; color:white\" ><p>대여취소</p></button>\r\n");
      out.write("                                   	</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                		}
                	
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-wrapper\">\r\n");
      out.write("            <p>\r\n");
      out.write("                Copyright (C) 2022 All Rights Reserved.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/aos@next/dist/aos.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    AOS.init({\r\n");
      out.write("        once: true\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $('.moreboxBtn').click(function(){\r\n");
      out.write("        $('.morebox').css('display','flex');\r\n");
      out.write("        $('.moreboxBtn').css('display','none');\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write(" \r\n");
      out.write("        $(\".floating\").hide();\r\n");
      out.write("        $(function() {\r\n");
      out.write(" \r\n");
      out.write("            $(window).scroll(function() {\r\n");
      out.write("                if ($(this).scrollTop() > 200) {\r\n");
      out.write("                    $('.floating').fadeIn();\r\n");
      out.write("                } else {\r\n");
      out.write("                    $('.floating').fadeOut();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write(" \r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    $(function () {\r\n");
      out.write("        $('.floating a, .logo').click(function (e) {\r\n");
      out.write("            $.scrollTo(this.hash || 0, 500); /* 속도 절, 숫자가 작을수록 빠름 */\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    if (window.navigator.userAgent.match(/MSIE|Internet Explorer|Trident/i)) {\r\n");
      out.write("        // IE!!\r\n");
      out.write("        window.location = 'https://support.microsoft.com/ko-kr/office/%ec%97%b0%ea%b2%b0%ed%95%98%eb%a0%a4%eb%8a%94-%ec%9b%b9-%ec%82%ac%ec%9d%b4%ed%8a%b8%ea%b0%80-internet-explorer%ec%97%90%ec%84%9c-%ec%9e%91%eb%8f%99%ed%95%98%ec%a7%80-%ec%95%8a%ec%8a%b5%eb%8b%88%eb%8b%a4-8f5fc675-cd47-414c-9535-12821ddfc554?ui=ko-kr&rs=ko-kr&ad=kr';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
